### ISSUE TITLE
Issue with running the demo file

### ISSUE THREAD

**Issue by subbulakshmisubha** [scaelles/DEXTR-PyTorch#27]
I am currently trying to run the demo file, I have downloaded the model and followed the steps as given in the page but when I run demo.py I get this. It runs indefinitely. It doesn't seem to be proceeding beyond this. 

Dilations: (2, 4)
Number of classes: 1
Number of Input Channels: 4
Initializing classifier: PSP
Initializing weights from: models/dextr_pascal-sbd.pth

Can anyone help me with this if they faced a similar issue?

**Comment by subbulakshmisubha** [comment]
Also if this is an issue with respect to the UI display which version of QT should be installed? And any version of tkinter to be installed?

**Comment by scaelles** [comment]
Hello,
I am not sure if the problem is loading the weights or displaying the image. I would recommend you to print something after loading of the network has finished in line 37 in `demo.py`
If it loads correctly, then I would suggest that you check matplotlib works in your machine. I don't think that the UI display software version for our code should be any special version.
