### ISSUE TITLE
train_pascal.py doesn't work

### ISSUE THREAD

**Issue by ascust** [scaelles/DEXTR-PyTorch#4]
Hi,
I tried to run "train_pascal.py" but failed to do so. I found something confusing. In your code,
```
if resume_epoch == 0:
    print("Initializing from pretrained Deeplab-v2 model")
else:
...
```
It seems there is nothing done here if we start from the beginning. I am curious how you convert the first conv layer from RGB 3 channels to 4 channels.

**Comment by kmaninis** [comment]
Hi,

The if-else for resume_epoch is used to load an intermediate model from a checkpoint, so it does not do anything if training starts from epoch 0.

For the 4th channel, please take a look in this part of the code: https://github.com/scaelles/DEXTR-PyTorch/blob/34cc23b6667edebde7c261eaf678ddf48d8aca13/networks/deeplab_resnet.py#L203

Please tell us more about the error you are getting, so that we can help more specifically.

**Comment by ascust** [comment]
@kmaninis Okay, that makes more sense. Would you mind answering another question? From this part, it uses the weights from the last channel to initialise the new channel. Is there a particular reason for this? In other words, what if I use Gaussian to initialise the last channel? I am asking this because it seems the heatmap for extreme points is not like images in terms of the features, why do we use the same filters for that?

**Comment by kmaninis** [comment]
There is no particular reason for this, we just thought that all weights along a layer should have similar scale. Extreme point heatmaps definitely do not look like an image, but nevertheless this approach works fine. I hope it helps.
